sudo: false
os:
  - linux
language: node_js
node_js:
  - '10'
  - '12'
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn lint
  - yarn test
branches:
  only:
    - master
